import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
// import theme from "./theme";
import { ThemeProvider } from "@emotion/react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppRouterCacheProvider options={{ enableCssLayer: true }}>
        {/* <ThemeProvider theme={theme} > */}
          <body className={inter.className}>{children}</body>
        {/* </ThemeProvider> */}
      </AppRouterCacheProvider>
    </html>
  );
}
